theme: jekyll-theme-minimal
title: Shiyan Wei
description: |
  Hi, I am a Finance Ph.D. Candidate at the Paul Merage School of Business, University of California, Irvine. 
  My research interests include the Financial Market, Institutional Investor, and Real Estate.